title: Blog
author: Thorsten Picard
email: # your-email@domain.com
description: 

# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  thorstenpicard

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
